{
 "title": "healthstats",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "steps",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "steps" }
   ]
  },
  {
   "title": "floors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "floor(floors_ascended)" }
   ]
  },
  {
   "title": "intensity minutes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "m",
   "valueName": "current",
   "targets": [
    {
     "expr": "intensity_minutes_moderate + intensity_minutes_vigorous * 2"
    }
   ]
  },
  {
   "title": "weight",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "masskg",
   "valueName": "current",
   "targets": [
    { "expr": "weight_total" }
   ]
  },
  {
   "title": "body fat",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "weight_body_fat" }
   ]
  },
  {
   "title": "muscle mass",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "masskg",
   "valueName": "current",
   "targets": [
    { "expr": "weight_muscle_mass" }
   ]
  },
  {
   "title": "calories",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "calories" }
   ]
  },
  {
   "title": "resting heart rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "resting_heart_rate" }
   ]
  },
  {
   "title": "sleep",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "sleep_time_sec" }
   ]
  },
  {
   "title": "deep sleep",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "sleep_deep_sec" }
   ]
  },
  {
   "title": "last sync time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(push_time_seconds) * 1000",
     "legendFormat": "last sync time"
    }
   ]
  },
  {
   "title": "last sync time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(push_time_seconds) * 1000",
     "legendFormat": "last sync time"
    }
   ]
  },
  { "title": "weight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "weight",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    { "expr": "weight_total", "legendFormat": "weight in kg" }
   ]
  },
  {
   "title": "body fat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "weight_body_fat", "legendFormat": "body fat %" }
   ]
  },
  {
   "title": "muscle mass",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "masskg" }
   ],
   "targets": [
    { "expr": "weight_muscle_mass", "legendFormat": "muscle mass in kg" }
   ]
  },
  {
   "title": "body water",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "weight_body_water", "legendFormat": "body water %" }
   ]
  },
  {
   "title": "steps - calories - intensity minutes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "steps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "steps", "legendFormat": "total steps" },
    { "expr": "steps_daily_goal", "legendFormat": "daily steps goal" }
   ]
  },
  {
   "title": "calories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "calories", "legendFormat": "total calories" },
    { "expr": "calories_active", "legendFormat": "active calories" },
    { "expr": "calories_resting", "legendFormat": "resting calories" }
   ]
  },
  {
   "title": "intensity minutes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "intensity_minutes_moderate + intensity_minutes_vigorous * 2",
     "legendFormat": "total intensity minutes"
    },
    { "expr": "intensity_minutes_moderate", "legendFormat": "moderate intensity minutes" },
    { "expr": "intensity_minutes_vigorous", "legendFormat": "vigorous intensity minutes" }
   ]
  },
  {
   "title": "sleep - movement - resting heart rate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "sleep",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "sleep_time_sec", "legendFormat": "total sleep time" },
    { "expr": "sleep_deep_sec", "legendFormat": "deep sleep time" },
    { "expr": "sleep_light_sec", "legendFormat": "light sleep time" },
    { "expr": "sleep_awake_sec", "legendFormat": "awake time" }
   ]
  },
  {
   "title": "active vs sedentary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "active_seconds", "legendFormat": "active" },
    { "expr": "sedentary_seconds", "legendFormat": "sedentary" }
   ]
  },
  {
   "title": "resting heart rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "resting_heart_rate", "legendFormat": "heart rate" }
   ]
  }
 ]
}